language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t mfcosta/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true mfcosta/docker-react npm run test